### ISSUE TITLE
In installing receive the error "error:0308010C:digital envelope routines::unsupported"

### ISSUE THREAD

**Issue by MirtoBusico** [piral-samples/piral-microfrontend-demo#45]
Triyng to follow the instructions in readme launching "./install.sh" file I always receive errors.
Trying to generate evgery application, for the app-shell, the command "npm run build" gives the error "Error: error:0308010C:digital envelope routines::unsupported" 

What can I do?

Session transcript:

```
sysop@m01serv:~/software/test/PIRAL/piral-microfrontend-demo$ cd app-shell/
sysop@m01serv:~/software/test/PIRAL/piral-microfrontend-demo/app-shell$ npm i

up to date, audited 870 packages in 1s

77 packages are looking for funding
  run `npm fund` for details

7 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
sysop@m01serv:~/software/test/PIRAL/piral-microfrontend-demo/app-shell$ npm run build

> app-shell@1.0.0 build
> piral build

Bundle emulator ...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/loader-runner/lib/LoaderRunner.js:186:6
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/node_modules/loader-runner/lib/LoaderRunner.js:221:10) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.0
sysop@m01serv:~/software/test/PIRAL/piral-microfrontend-demo/app-shell$ 

```

**Comment by FlorianRappl** [comment]
I've not seen it - I would recommend trying to use a different version of Node, e.g., v16.

Also this seems to be the recommendation from others, e.g., on SO: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by FlorianRappl** [comment]
Alternatively, you can replace `piral-cli-webpack` with `piral-cli-webpack5`. This issue seems to be specific to Webpack v4 and is fixed in Webpack v5.

**Comment by MirtoBusico** [comment]
Well trying to update to piral-cli-webpack5 (in app-scall directory issued "npm install piral-webpack5") I updated package.json to:
```
{
  "name": "app-shell",
  "version": "1.0.0",
  "description": "The App Shell - application to be deployed.",
  "keywords": [
    "piral"
  ],
  "dependencies": {
    "piral": "0.14.0",
    "piral-cli-webpack5": "^0.14.23",
    "piral-containers": "0.14.0"
  },
  "scripts": {
    "start": "piral debug",
    "build": "piral build"
  },
  "app": "./src/index.html",
  "main": "lib/index.js",
  "pilets": {
    "files": [
      ".editorconfig",
      "prettier.config.js"
    ],
    "externals": [],
    "devDependencies": {},
    "scripts": {}
  },
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@types/react-router": "latest",
    "@types/react-router-dom": "latest",
    "piral-cli": "0.14.0",
    "piral-cli-webpack5": "^0.14.23",
    "typescript": "latest"
  }
}

```

But now I receive the error "Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string."

```
sysop@m01serv:~/software/test/PIRAL/piral-microfrontend-demo/app-shell$ npm run build

> app-shell@1.0.0 build
> piral build

Bundle emulator ...
asset index.b044c8.js 1.61 MiB [emitted] [immutable] (name: main) 1 related asset
asset index.html 318 bytes [emitted]
orphan modules 989 KiB [orphan] 74 modules
runtime modules 2.37 KiB 7 modules
modules by path ./node_modules/ 1.44 MiB 165 modules
modules by path ./src/ 9.76 KiB
  ./src/page.css 357 bytes [built] [code generated]
  ./src/index.tsx 771 bytes [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./src/page.css 8.66 KiB [built] [code generated]
webpack 5.72.0 compiled successfully in 1285 ms
🚨  [0076] Could not create the declaration in "/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell". Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
✨  Emulator package available in "/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/dist/emulator".
Bundle release ...
asset index.9982b0.js 232 KiB [emitted] [immutable] [minimized] (name: main) 1 related asset
asset main.bf2594.css 2.34 KiB [emitted] [immutable] [minimized] (name: main) 1 related asset
asset index.html 359 bytes [emitted]
Entrypoint main 234 KiB (769 KiB) = main.bf2594.css 2.34 KiB index.9982b0.js 232 KiB 2 auxiliary assets
orphan modules 345 KiB [orphan] 184 modules
runtime modules 2.25 KiB 6 modules
cacheable modules 407 KiB (javascript) 3.04 KiB (css/mini-extract)
  modules by path ./node_modules/ 212 KiB 19 modules
  modules by path ./src/ 195 KiB (javascript) 3.04 KiB (css/mini-extract)
    ./src/page.css 50 bytes [built] [code generated]
    ./src/index.tsx + 110 modules 195 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./src/page.css 3.04 KiB [built] [code generated]
webpack 5.72.0 compiled successfully in 3195 ms
✨  Files for publication available in "/home/sysop/software/test/PIRAL/piral-microfrontend-demo/app-shell/dist/release".
sysop@m01serv:~/software/test/PIRAL/piral-microfrontend-demo/app-shell$
```

Any hint?

**Comment by FlorianRappl** [comment]
I'd ignore this. It just means that the declaration could not be build. This is a bug that Node 17 dropped support for the "exports" field trailing slash notation. It only accepts the star notation now.

As you see the thing builds and it should also work when you run it.

**Comment by MirtoBusico** [comment]
Well one step ahead.
For team-blue I had to issue

- npm i
- npm install piral-cli-webpack5
- change package.json
- npm audit fix --force
- npm run build
- npm run upload

Now trying to do the same for the other two piled and test the application

**Comment by MirtoBusico** [comment]
Well, another step ahead.

I was able to build and upload the three pilets.

Issuing "./run.sh" in the project directory I have:

An empty app-shell with a console error
<img width="1290" alt="ksnip_20220504-155331" src="https://user-images.githubusercontent.com/11090934/166697668-98d1b830-c786-424f-95dc-a2f460a1e025.png">

A feed service showing the three pilets
<img width="830" alt="ksnip_20220504-155413" src="https://user-images.githubusercontent.com/11090934/166697805-1454ce9a-06df-4113-8623-bf678faf163d.png">

and a kras server (I don't know what it is) showing
<img width="693" alt="ksnip_20220504-155451" src="https://user-images.githubusercontent.com/11090934/166697957-3fe2489b-f1e4-4015-9ffc-3bd2bd9cd225.png">

What can I do?

**Comment by FlorianRappl** [comment]
The problem is already in your build process. I am not sure what you did - because for me it just works - but since `process` is not defined it seems you work with a custom or invalid webpack configuration.

Make sure to use the right version.

Maybe just pull from `main` (I've seen you installed some bundler, but a version that is not aligned with the `piral-cli`) and restart from there.

**Comment by MirtoBusico** [comment]
Well, for the first try:

Started a local feed service

Then, for every team:
-     npm i
-     npm install piral-cli-webpack5
-     change package.json
-     npm audit fix --force
-     npm run build
-     npm run upload
 

Verified that the pilets were loaded

Then started the layout  with npm start

For the second try I just ran the "./run.sh" in the project home

The result was the same: an empty red frame

Now I'll verify the entire process

**Comment by FlorianRappl** [comment]
What I did (and I tried it on 2 machines, so this just works):

1. Clone the repo
2. Run `install.sh`
3. Run `run.sh` 

All working. I'll close this one.
